// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// RatingView represents a row from 'public.rating_view'.
type RatingView struct {
	Game        sql.NullInt64 `json:"game"`         // game
	TotalRating sql.NullInt64 `json:"total_rating"` // total_rating
	Count       sql.NullInt64 `json:"count"`        // count
}

type RatingViewService interface {
	DoesRatingViewExists(rv *RatingView) (bool, error)
	InsertRatingView(rv *RatingView) error
	UpdateRatingView(rv *RatingView) error
	UpsertRatingView(rv *RatingView) error
	DeleteRatingView(rv *RatingView) error
	GetAllRatingViews() ([]*RatingView, error)
	GetChunkedRatingViews(limit int, offset int) ([]*RatingView, error)
}

type RatingViewServiceImpl struct {
	DB XODB
}
